## Housing Problem

In [34]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pandas as pd
import os

In [10]:
X, y = fetch_california_housing(return_X_y=True)

In [14]:
california = fetch_california_housing()

In [15]:
dir(california)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [17]:
print(california.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [28]:
model = LinearRegression()

In [29]:
model.fit(X_train,y_train)

LinearRegression()

In [32]:
y_pred = model.predict(X_test[:1])
y_pred

array([0.72563462])

In [33]:
y_test[:1]

array([0.477])

## Salary Prediction

In [35]:
curdir = os.getcwd()
sal_data_path = os.path.join(curdir,"..","Datasets","Salary_Data.csv")
sal_df = pd.read_csv(sal_data_path)

In [36]:
sal_df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [41]:
X = sal_df.iloc[:,:-1].values
y = sal_df.iloc[:,-1].values

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [45]:
model = LinearRegression()

In [46]:
model.fit(X_train,y_train)

LinearRegression()

In [47]:
y_pred = model.predict(X_test[:5])

In [48]:
y_pred

array([115814.30756236,  71511.92534771, 102617.85328566,  75282.34085534,
        55487.65944028])

In [49]:
y_test[:5]

array([112635.,  67938., 113812.,  83088.,  64445.])

In [50]:
model.score(X_test,y_test)

0.9553063138044949

In [63]:
yrs = int(input("How many years of experience do you have:"))
sal = model.predict(np.array([yrs]).reshape(-1,1))
print("Your predicted salary:",round(sal[0],3))

How many years of experience do you have: 8


Your predicted salary: 100732.646
